POST http://localhost:5000/login
Content-Type: application/json

{
  "login": "pedro.silva",
  "password": "master"
}

> {% client.global.set("idUser", response.body.json.id); %}

### Create consumer individual / Criando cliente pessoa fisica
POST http://localhost:5000/client
Content-Type: application/json

{
  "userID": {{idUser}},
  "phone": "(62) 91111-1111",
  "individualConsumer": {
    "ir": "111.111.111-11",
    "name": "Pedro Silva"
  }
}

### Create consumer individual / Criando cliente pessoa fisica
POST http://localhost:5000/client
Content-Type: application/json

{
  "userID": {{idUser}},
  "phone": "(62) 91111-1111",
  "legalConsumer": {
    "cnpj": "11.1111.111/0001-11",
    "corporateName": "Pedro Silva",
    "trade": "NEXDEV"
  }
}
